-- TẠO DATABASE
CREATE DATABASE BTLPython
GO

USE BTLPython
GO

-- TẠO BẢNG
CREATE TABLE Works
(
	Khoi INT NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	NamST INT NOT NULL,
	NamXB INT NOT NULL,
	TheLoai NVARCHAR(50) NOT NULL,
	ND NTEXT NOT NULL,
	TacGia NVARCHAR(50) NOT NULL,
	NamSinh INT NOT NULL,
	NamMat INT NOT NULL,
	Que NVARCHAR(20) NOT NULL
)

